#pragma once
//OpenGL Defines
#define OPENGL_SUPRESS_NOTIFICATION

//Tinyglft Defines
#define TINYGLTF_IMPLEMENTATION
#define STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION

//Current Project
#define LOAD_GLTF_MESH