#pragma once
#define OPENGL_SUPRESS_NOTIFICATION

//TINYGLTF DEFINES
#define TINYGLTF_IMPLEMENTATION
#define STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION

//Current Project
#define LOAD_GLTF_MESH